SELECT 
    C.NOMBRE_CLIENTE || ' ' || C.APE1 AS CLIENTE_COMPLETO,
    COUNT(DISTINCT P.ID_PEDIDO) AS TOTAL_PEDIDOS,
    SUM(PP.CANTIDAD) AS TOTAL_PRODUCTOS,
    MAX(P.FECHA_COMPRA) AS ULTIMA_COMPRA
FROM CLIENTE C
JOIN PEDIDO P ON C.ID_USUARIO = P.ID_CLIENTE
JOIN PEDIDO_PRODUCTO PP ON P.ID_PEDIDO = PP.ID_PEDIDO
WHERE P.FECHA_COMPRA BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD') 
                         AND TO_DATE('2024-12-31', 'YYYY-MM-DD')
GROUP BY C.NOMBRE_CLIENTE, C.APE1
HAVING SUM(PP.CANTIDAD) > 5 
   OR COUNT(DISTINCT P.ID_PEDIDO) >= 3;