--SELECT PARA SABER EL TOTAL DE GANANCIAS DE CADA VENDEDOR QUE HA CONSEGUIDO VENDER ALGUN PRODUCTO

SELECT V.NOMBRE_VENDEDOR||' '||V.APE1 AS "NOMBRE VENDEDOR", SUM(UN_PRODS.TOTAL_LINEA) AS "TOTAL GANANCIAS"
FROM(
SELECT 
    PROD.ID_PRODUCTO,
    PROD.ID_VENDEDOR AS VENDEDOR,
    PROD.NOMBRE AS NOMBRE_PRODUCTO,
    R.PRECIO AS PRECIO_UNITARIO,
    PED_PROD.CANTIDAD,
    (R.PRECIO * PED_PROD.CANTIDAD) AS TOTAL_LINEA
FROM PEDIDO_PRODUCTO PED_PROD
JOIN PRODUCTO PROD ON PED_PROD.ID_PRODUCTO = PROD.ID_PRODUCTO
JOIN ROPA R ON PROD.ID_PRODUCTO = R.ID_PRODUCTO

UNION ALL

SELECT 
    PROD.ID_PRODUCTO,
    PROD.ID_VENDEDOR AS VENDEDOR,
    PROD.NOMBRE AS NOMBRE_PRODUCTO,
    AC.PRECIO AS PRECIO_UNITARIO,
    PED_PROD.CANTIDAD,
    (AC.PRECIO * PED_PROD.CANTIDAD) AS TOTAL_LINEA
FROM PEDIDO_PRODUCTO PED_PROD
JOIN PRODUCTO PROD ON PED_PROD.ID_PRODUCTO = PROD.ID_PRODUCTO
JOIN ACCESORIOS AC ON PROD.ID_PRODUCTO = AC.ID_PRODUCTO
) UN_PRODS
JOIN VENDEDOR V ON UN_PRODS.VENDEDOR = V.ID_USUARIO
GROUP BY V.NOMBRE_VENDEDOR||' '||V.APE1 ;


