SELECT ACCESORIOS.ID_ACCESORIO, PRODUCTO.NOMBRE, ACCESORIOS.PRECIO
FROM ACCESORIOS
JOIN PRODUCTO ON ACCESORIOS.ID_PRODUCTO = PRODUCTO.ID_PRODUCTO;


SELECT CLIENTE.NOMBRE_CLIENTE, CLIENTE.APE1, CLIENTE.APE2, PEDIDO.ID_PEDIDO, PEDIDO.FECHA_COMPRA
FROM CLIENTE
INNER JOIN PEDIDO ON CLIENTE.ID_USUARIO = PEDIDO.ID_CLIENTE;


SELECT ID_USUARIO, NOMBRE_USUARIO, EMAIL, FECHA_ALTA
FROM USUARIO
ORDER BY FECHA_ALTA DESC;

SELECT ID_USUARIO, NOMBRE_VENDEDOR, COMISION
FROM VENDEDOR
WHERE COMISION > 1000;

SELECT USUARIO.ID_USUARIO, USUARIO.NOMBRE_USUARIO, VENDEDOR.NOMBRE_VENDEDOR, VENDEDOR.COMISION
FROM USUARIO
LEFT JOIN VENDEDOR ON USUARIO.ID_USUARIO = VENDEDOR.ID_USUARIO;

