SELECT P.NOMBRE AS NOMBRE_PRODUCTO,
SUM(R.PRECIO) AS PRECIO_TOTAL_ROPA,
SUM(A.PRECIO) AS PRECIO_TOTAL_ACCESORIOS
FROM PRODUCTO P
JOIN ROPA R ON P.ID_PRODUCTO = R.ID_PRODUCTO
JOIN ACCESORIOS A ON P.ID_PRODUCTO = A.ID_PRODUCTO
JOIN    PEDIDO_PRODUCTO PP ON P.ID_PRODUCTO = PP.ID_PRODUCTO
GROUP BY P.NOMBRE
HAVING SUM(r.PRECIO) > 200 OR SUM(a.PRECIO) > 200;